Return NotEnoughAccountKeys if address is not found.
Cyber-Core/solana-program-library pull request #211
Opened 2021-05-21 18:55 UTC by vasiliy-zaznobin

2021-05-24 17:25 UTC, vasiliy-zaznobin commented
All checks will pass after https://github.com/neonlabsorg/solana-program-library/pull/214

2021-05-25 07:28 UTC, sinev-valentine requested changes

2021-05-25 07:28 UTC, sinev-valentine commented on evm_loader/program/src/account_storage.rs
> +                        debug_print!("Not found account for {:?}.", address);
This message is used in the function find_account().
Interpretation may be ambiguous.
Please enter other message.

2021-05-25 08:17 UTC, sinev-valentine approved these changes

2021-05-25 08:20 UTC, merged